[package]
name = "ziped"
version = "0.1.0"
edition = "2021"

[dependencies]
encoding_rs = "0.8.32"
glob = "0.3.1"
tempfile = "3.5.0"
wildmatch = "2.1.1"
zip = { git="https://github.com/hidez8891/zip-rs/" , branch="dev/ziped" }
